# Generated by Django 2.0.2 on 2018-03-07 19:06

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('external', models.BooleanField(help_text='Is this asset stored inside the company or outside')),
                ('content_type', models.CharField(help_text='Asset content-type', max_length=255)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Meta data associated with this asset')),
                ('owner', models.ForeignKey(help_text='Owner of this asset', on_delete=django.db.models.deletion.PROTECT, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
