# Generated by Django 2.0.2 on 2018-03-07 17:41

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the session')),
                ('place', models.CharField(help_text='Place where the session took place', max_length=1025)),
                ('duration', models.DurationField(help_text="Session's duration")),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Additionnal data regarding this session')),
                ('owner', models.ForeignKey(help_text='Owner of the sporting session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, help_text='At what time of the day the recording started', null=True)),
                ('asset', models.ForeignKey(help_text='Video asset', on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='assets.Asset')),
                ('session', models.ForeignKey(help_text='Session associated with this video', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sports.Session')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField(help_text='Frame number for this point')),
                ('time', models.DurationField(help_text='Time of this point in the video')),
                ('video', models.ForeignKey(help_text='Video associated with this point', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sports.Video')),
            ],
        ),
    ]
