# Generated by Django 2.0.2 on 2018-03-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='index',
            field=models.IntegerField(default=0, help_text='If there are multiple videos for one session, index represents the time-related order. i.e. video with index 0 was shot before video with index 1'),
        ),
    ]
