# Generated by Django 2.0.3 on 2018-03-27 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_video_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='session',
            field=models.ForeignKey(help_text='Session associated with this video', on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='sports.Session'),
        ),
        migrations.AlterUniqueTogether(
            name='videopoint',
            unique_together={('video', 'frame', 'time')},
        ),
    ]
