# Generated by Django 2.0.3 on 2018-04-04 12:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='Id of the generic object corresponding to these stats')),
                ('computed_at', models.DateTimeField(help_text='When were these stats computed')),
                ('date', models.DateField(help_text='At what point in time these stats are valid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='The actual stats')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='Type of the generic object corresponding to these stats', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
