version: 2
defaults: &defaults
  working_directory: ~/project
jobs:
  build:
    <<: *defaults
    docker:
      - image: gobadiah/docker-vault:0.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ./devops/bin/circleci build
  test:
    <<: *defaults
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
  deploy:
    <<: *defaults
    docker:
      - image: gobadiah/docker-vault:0.3
    steps:
      - checkout
      - run:
          command: |
            ./devops/bin/circleci deploy
workflows:
  version: 2
  core:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
