#!/usr/local/bin/zsh

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
TMP="$SCRIPTPATH/tmp"

ENV=${ENV:=staging}

source $SCRIPTPATH/../config

source $SCRIPTPATH/lib

destroy_api_app

destroy_web_app
