#!/usr/local/bin/zsh

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
TMP="$SCRIPTPATH/tmp"

source $SCRIPTPATH/../config

source $SCRIPTPATH/lib

create_web_app

configure_web_app

create_api_app

configure_api_app

heroku_login

deploy_web_app

deploy_api_app
