---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: kube-system
  labels:
    task: logging
    k8s-app: logstash
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /config/pipeline.conf
    xpack.monitoring.enabled: false
  pipeline.conf: "
    input {
      beats {
        port => 5044
        type => \"kube-logs\"
        ssl => false
      }
    }
    output {
      amazon_es {
        hosts => \"search-default-7a4pigdo4f5l6esdtgsxxjcjrq.eu-west-1.es.amazonaws.com\"
        region => \"eu-west-1\"
      }
    }"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: logging
        k8s-app: logstash
    spec:
      containers:
      - name: logstash
        image: gobadiah/logstash-es
        args: ["--path.settings", "/config"]
        volumeMounts:
        - name: config
          mountPath: /config
      securityContext:
        fsGroup: 101
      volumes:
      - name: config
        configMap:
          name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: logging
    kubernetes.io/name: logstash
  name: logstash
  namespace: kube-system
spec:
  ports:
  - port: 5044
    targetPort: 5044
    name: lumberjack
  selector:
    k8s-app: logstash
