# Generated by Django 2.0.3 on 2018-03-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setplayer',
            old_name='tennis_set',
            new_name='set',
        ),
    ]
