# Generated by Django 2.0.3 on 2018-03-27 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_auto_20180327_1217'),
        ('tennis', '0002_auto_20180327_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(help_text='Corresponding player', on_delete=django.db.models.deletion.CASCADE, to='tennis.Player')),
                ('session', models.ForeignKey(help_text='Corresponding session', on_delete=django.db.models.deletion.CASCADE, to='sports.Session')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='sessions',
            field=models.ManyToManyField(help_text='Sessions in which this player participated', related_name='players', through='tennis.SessionPlayer', to='sports.Session'),
        ),
    ]
