# Generated by Django 2.0.3 on 2018-03-29 11:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0002_auto_20180327_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tennis club'),
        ),
        migrations.AddField(
            model_name='user',
            name='dominant_hand',
            field=models.CharField(blank=True, choices=[('left_handed', 'left-handed'), ('right_handed', 'right-handed')], default='right_handed', max_length=255, null=True, verbose_name='Dominant hand'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='user',
            name='ranking',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ranking'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date(2018, 3, 29), verbose_name='Birthday'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Last name'),
        ),
    ]
