# Generated by Django 2.0.4 on 2018-05-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180509_1001'),
        ('core', '0003_auto_20180329_1139'),
    ]

    operations = [
    ]
